const EN = {
  modeCoding: 'Coding',
  modeDaily: 'Daily',
  modeCodingDescription: 'Implementation, tools, plans and verification',
  modeDailyDescription: 'Conversation, research, notes and light tasks',
  chooseMode: 'Choose how to work in this session',
  startSetup: 'Start setup',
  startCenter: 'Start center',
  newConversation: 'New conversation',
  newConversationDescription: 'Start with a clean context',
  continueConversation: 'Continue current session',
  continueDescription: 'Return to the active conversation',
  resumeSession: 'Resume session',
  startupSettings: 'Settings',
  shortcutsDescription: 'Commands and navigation',
  settingsClose: '↑↓ select · ←→ / Space change · Esc close',
  settingMode: 'Work mode',
  settingLocation: 'Location',
  settingReasoning: 'Reasoning effort',
  settingApproval: 'Approval mode',
  settingSandbox: 'Sandbox access',
  settingSoul: 'Persona',
  settingValues: {
    coding: 'Coding', daily: 'Daily', workspace: 'Default workspace', cwd: 'Current directory', off: 'Off', auto: 'Auto', low: 'Low', medium: 'Medium', high: 'High',
    review: 'Review', full_access: 'Full access', 'read-only': 'Read only', 'workspace-write': 'Workspace write', 'danger-full-access': 'Full system access'
  },
  modelLabel: 'MODEL',
  accessLabel: 'ACCESS',
  entering: 'Entering…',
  homeKeys: '↑↓ navigate · Enter open · Ctrl+C exit',
  ready: 'Ready',
  thinking: 'Thinking…',
  generating: 'Writing response…',
  working: 'Working…',
  sending: 'Sending…',
  stopping: 'Stopping…',
  stopped: 'Stopped',
  continuedInNewSession: 'Stopped — continued in a new conversation',
  queued: (count) => `${count} queued`,
  queueTitle: 'Queued',
  queueJump: '· Ctrl+Enter to jump the queue',
  helpTitle: 'Keyboard shortcuts',
  approvalTitle: 'Permission required',
  approve: 'Approve once',
  approveDescription: 'Allow this action once',
  reject: 'Reject',
  rejectDescription: 'Do not run this action',
  approvalQuestion: 'Allow the requested tool action?',
  imageAttachment: 'Image attachment',
  toolCalls: (count) => `${count} tool call${count === 1 ? '' : 's'}`,
  detailArguments: 'arguments',
  detailResult: 'result',
  detailChange: 'change',
  detailChanges: 'changes',
  running: (count) => `${count} running`,
  failed: (count) => `${count} failed`,
  reasoningLive: 'Thinking',
  reasoningDone: (duration) => `Thought for ${duration}`,
  plan: 'Plan',
  todos: 'Tasks',
  todosEmpty: 'No active tasks',
  switchedMode: (mode) => `Switched to ${mode} mode`,
  exitAgain: 'Press Ctrl+C again to exit',
  processExpanded: 'Process details expanded',
  processCollapsed: 'Process details collapsed',
  actionFailed: 'Action failed',
  activityKeys: '/ commands  Ctrl+O details  Ctrl+T view',
  helpClose: 'Esc / Enter to close',
  shortcutRows: [
    ['Enter', 'send'], ['Ctrl+Enter', 'send / jump queue'], ['Shift+Enter / Ctrl+J', 'new line'], ['↑ / ↓', 'input history'],
    ['Wheel / Shift+↑ / ↓', 'scroll conversation'], ['PageUp / PageDown', 'scroll one page'],
    ['Ctrl+Shift+↑ / ↓', 'jump prompts'],
    ['/', 'commands'], ['Ctrl+O / /tools', 'process details'], ['Ctrl+T', 'body only / full'], ['Esc', 'stop / home'],
    ['Ctrl+C', 'clear / exit']
  ],
  emptyHint: 'Type / for commands, @ for files and ! for shell.',
  shortcutHint: 'Wheel/Shift+↑↓ scroll · ↑↓ history · Ctrl+O details · Ctrl+T view',
  processed: 'Processed',
  showFull: 'Ctrl+T full',
  showBodyOnly: 'Ctrl+T body only',
  bodyOnlyView: 'Body only',
  fullView: 'Full view',
  compact: 'Compact context',
  dream: 'Consolidate memories',
  reflect: 'Reflect session into a skill',
  inbox: 'Show memory inbox',
  history: 'Open session history',
  sessionHistory: 'Session history',
  generalChat: 'General Chat',
  projects: 'Projects',
  unknownProject: 'Unknown project',
  chooseSessionGroup: 'Choose a conversation space',
  historyBack: 'Esc back',
  sessionCount: (count) => `${count} session${count === 1 ? '' : 's'}`,
  noSessions: 'No saved conversations yet',
  historyDescription: 'Browse and resume conversations',
  messages: 'messages',
  commandGroup: 'TOOL',
  skillGroup: 'SKILL',
  help: 'Show keyboard shortcuts',
  tools: 'Toggle process details',
  codingMode: 'Switch to coding mode',
  dailyMode: 'Switch to daily mode',
  towerMode: 'Switch to tower mode',
  towerOn: 'Tower on',
  towerOff: 'Tower off',
  towerFailed: 'Could not change tower mode',
  towerBusy: 'Cannot switch tower while a request is running'
};

const ZH = {
  ...EN,
  modeCoding: '编码模式',
  modeDaily: '日常模式',
  modeCodingDescription: '实现、工具调用、计划与验证',
  modeDailyDescription: '对话、研究、整理与轻任务',
  chooseMode: '选择这次会话的工作方式',
  startSetup: '开始设置',
  startCenter: '启动中心',
  newConversation: '新对话',
  newConversationDescription: '从干净上下文开始',
  continueConversation: '继续当前会话',
  continueDescription: '返回正在进行的对话',
  resumeSession: '继续会话',
  startupSettings: '设置',
  shortcutsDescription: '命令与导航方式',
  settingsClose: '↑↓ 选择 · ←→ / Space 更改 · Esc 关闭',
  settingMode: '工作模式',
  settingLocation: '工作位置',
  settingReasoning: '思考强度',
  settingApproval: '审批模式',
  settingSandbox: '沙箱权限',
  settingSoul: '人格',
  settingValues: {
    coding: '编码', daily: '日常', workspace: '默认 Workspace', cwd: '当前目录', off: '关闭', auto: '自动', low: '低', medium: '中', high: '高',
    review: '逐项审批', full_access: '完全放行', 'read-only': '只读', 'workspace-write': '工作区写入', 'danger-full-access': '完整系统权限'
  },
  modelLabel: '模型',
  accessLabel: '权限',
  entering: '正在进入…',
  homeKeys: '↑↓ 移动 · Enter 打开 · Ctrl+C 退出',
  ready: '就绪',
  thinking: '思考中…',
  generating: '正在回答…',
  working: '处理中…',
  sending: '正在发送…',
  stopping: '正在停止…',
  stopped: '已停止',
  continuedInNewSession: '已停止，已在新会话中继续',
  queued: (count) => `队列中 ${count} 条`,
  queueTitle: '待发送',
  queueJump: '· Ctrl+Enter 插队',
  helpTitle: '快捷键',
  approvalTitle: '需要授权',
  approve: '仅本次允许',
  approveDescription: '只允许执行这一次',
  reject: '拒绝',
  rejectDescription: '不执行这项操作',
  approvalQuestion: '允许执行这项工具操作吗？',
  imageAttachment: '图片附件',
  toolCalls: (count) => `${count} 次工具调用`,
  detailArguments: '参数',
  detailResult: '结果',
  detailChange: '变更',
  detailChanges: '变更',
  running: (count) => `${count} 项运行中`,
  failed: (count) => `${count} 项失败`,
  reasoningLive: '正在思考',
  reasoningDone: (duration) => `思考了 ${duration}`,
  plan: '计划',
  todos: '任务',
  todosEmpty: '暂无任务',
  switchedMode: (mode) => `已切换到${mode === 'coding' ? '编码' : '日常'}模式`,
  exitAgain: '再次按 Ctrl+C 退出',
  processExpanded: '已展开过程详情',
  processCollapsed: '已折叠过程详情',
  actionFailed: '操作失败',
  activityKeys: '/ 命令  Ctrl+O 详情  Ctrl+T 视图',
  helpClose: 'Esc / Enter 关闭',
  shortcutRows: [
    ['Enter', '发送'], ['Ctrl+Enter', '发送 / 插队'], ['Shift+Enter / Ctrl+J', '换行'], ['↑ / ↓', '输入历史'],
    ['滚轮 / Shift+↑ / ↓', '滚动会话'], ['PageUp / PageDown', '整页滚动'],
    ['Ctrl+Shift+↑ / ↓', '跳转提问'],
    ['/', '命令'], ['Ctrl+O / /tools', '过程详情'], ['Ctrl+T', '只保留正文 / 完全'], ['Esc', '停止 / 返回首页'],
    ['Ctrl+C', '清空 / 退出']
  ],
  emptyHint: '输入 / 查看命令，@ 引用文件，! 执行 Shell。',
  shortcutHint: '滚轮/Shift+↑↓ 滚动 · ↑↓ 历史 · Ctrl+O 详情 · Ctrl+T 视图',
  processed: '已处理',
  showFull: 'Ctrl+T 完全',
  showBodyOnly: 'Ctrl+T 只保留正文',
  bodyOnlyView: '只保留正文',
  fullView: '完全',
  compact: '压缩当前上下文',
  dream: '整理长期记忆',
  reflect: '将本次会话沉淀为技能',
  inbox: '查看记忆收件箱',
  history: '打开会话历史',
  sessionHistory: '会话历史',
  generalChat: '普通会话',
  projects: '项目',
  unknownProject: '未知项目',
  chooseSessionGroup: '选择会话空间',
  historyBack: 'Esc 返回上一级',
  sessionCount: (count) => `${count} 个会话`,
  noSessions: '暂无历史会话',
  historyDescription: '浏览并继续历史对话',
  messages: '条消息',
  commandGroup: '工具',
  skillGroup: '技能',
  help: '查看键盘快捷键',
  tools: '展开或折叠过程详情',
  codingMode: '切换到编码模式',
  dailyMode: '切换到日常模式',
  towerMode: '切换到塔台模式',
  towerOn: '塔台已开启',
  towerOff: '塔台已关闭',
  towerFailed: '无法切换塔台',
  towerBusy: '请求进行中，无法切换塔台'
};

export function createTuiCopy(language = 'en') {
  return String(language).toLowerCase().startsWith('zh') ? ZH : EN;
}
