import { WEB_CONFIG_INTEGER_LIMITS } from '../../../shared/web-config-policy.js';
import { t } from "../../i18n/index.js";

export function buildSettingsFields() {
  return [
    {
      tab: "connection",
      path: "sdk.provider",
      control: "providerCards",
      optionsKey: "provider",
      label: t("provider"),
      help: t("providerHelp"),
    },
    {
      tab: "connection",
      path: "gateway.base_url",
      control: "input",
      label: t("baseUrl"),
      placeholder: "http://127.0.0.1:8000/v1",
      help: t("baseUrlHelp"),
    },
    {
      tab: "connection",
      path: "gateway.api_key",
      control: "input",
      type: "password",
      label: t("apiKey"),
      placeholder: "sk-...",
      help: t("apiKeyHelp"),
    },
    {
      tab: "connection",
      path: "model.name",
      control: "input",
      label: t("modelName"),
      placeholder: "gpt-4.1-mini",
      help: t("modelNameHelp"),
    },
    {
      tab: "connection",
      path: "model.fast_name",
      control: "input",
      label: t("fastModel"),
      placeholder: t("fastModelPlaceholder"),
      help: t("fastModelHelp"),
    },
    {
      tab: "connection",
      path: "gateway.timeout_ms",
      control: "number",
      label: t("timeout"),
      help: t("timeoutHelp"),
    },
    {
      tab: "connection",
      path: "gateway.max_retries",
      control: "number",
      label: t("maxRetries"),
      help: t("maxRetriesHelp"),
    },
    {
      tab: "model",
      path: "model.max_context_tokens",
      control: "number",
      label: t("maxContextTokens"),
      help: t("maxContextTokensHelp"),
    },
    {
      tab: "execution",
      path: "execution.mode",
      control: "choiceList",
      optionsKey: "executionMode",
      label: t("mode"),
      help: t("executionModeHelp"),
    },
    {
      tab: "execution",
      path: "execution.approval_mode",
      control: "choiceList",
      optionsKey: "approvalMode",
      label: t("approvalMode"),
      help: t("approvalModeHelp"),
    },
    {
      tab: "execution",
      path: "execution.max_steps",
      control: "number",
      label: t("agentMaxSteps"),
      help: t("agentMaxStepsHelp"),
      ...WEB_CONFIG_INTEGER_LIMITS["execution.max_steps"],
      step: 1,
      placeholder: "500",
    },
    {
      tab: "execution",
      path: "execution.incomplete_retries",
      control: "number",
      label: t("incompleteRetries"),
      help: t("incompleteRetriesHelp"),
      ...WEB_CONFIG_INTEGER_LIMITS["execution.incomplete_retries"],
      step: 1,
      placeholder: "3",
    },
    {
      tab: "execution",
      path: "sandbox.network",
      control: "input",
      label: t("sandboxNetwork"),
      help: t("sandboxNetworkHelp"),
      valueLabels: { none: t("sandboxNetworkNone"), "allow-all": t("sandboxNetworkAll") },
      cliExample: "codemini config set sandbox.network none",
    },
    {
      tab: "execution",
      path: "webui.terminal_enabled",
      control: "switch",
      label: t("reviewedTerminalEnabled"),
      help: t("reviewedTerminalEnabledHelp"),
      cliExample: "codemini config set webui.terminal_enabled true",
    },
    {
      tab: "execution",
      path: "sandbox.mode",
      control: "choiceList",
      optionsKey: "sandboxMode",
      label: t("sandboxMode"),
      help: t("sandboxModeHelp"),
    },
    {
      tab: "execution",
      path: "crew.max_workers",
      control: "number",
      label: t("crewMaxWorkers"),
      help: t("crewMaxWorkersHelp"),
      min: 1,
      max: 32,
    },
    {
      tab: "model",
      path: "ui.reply_language",
      control: "segmented",
      optionsKey: "replyLanguage",
      label: t("replyLanguage"),
      help: t("replyLanguageHelp"),
    },
    {
      tab: "web",
      path: "web.search_enabled",
      control: "switch",
      label: t("webSearchEnabled"),
      help: t("webSearchEnabledHelp"),
    },
    {
      tab: "web",
      path: "web.search_provider",
      control: "providerCards",
      optionsKey: "searchProvider",
      label: t("webSearchProvider"),
      help: t("webSearchProviderHelp"),
    },
    {
      tab: "web",
      path: "web.tavily_api_key",
      control: "input",
      type: "password",
      label: t("tavilyApiKey"),
      placeholder: t("tavilyApiKeyPlaceholder"),
      help: t("tavilyApiKeyHelp"),
      visibleWhen: ({ getValue }) => getValue("web.search_provider") === "tavily",
    },
    {
      tab: "web",
      path: "web.exa_api_key",
      control: "input",
      type: "password",
      label: t("exaApiKey"),
      placeholder: t("exaApiKeyPlaceholder"),
      help: t("exaApiKeyHelp"),
      visibleWhen: ({ getValue }) => getValue("web.search_provider") === "exa",
    },
    {
      tab: "web",
      path: "web.firecrawl_api_key",
      control: "input",
      type: "password",
      label: t("firecrawlApiKey"),
      placeholder: t("firecrawlApiKeyPlaceholder"),
      help: t("firecrawlApiKeyHelp"),
      visibleWhen: ({ getValue }) => getValue("web.search_provider") === "firecrawl",
    },
    {
      tab: "context",
      path: "context.preflight_trigger_pct",
      control: "percent",
      label: t("preflightTrigger"),
      placeholder: "60",
      help: t("preflightTriggerHelp"),
      min: 1,
      max: 100,
    },
    {
      tab: "context",
      path: "context.hard_limit_pct",
      control: "percent",
      label: t("hardLimit"),
      placeholder: "98",
      help: t("hardLimitHelp"),
      min: 1,
      max: 100,
    },
    {
      tab: "context",
      path: "context.tool_result_max_chars",
      control: "number",
      label: t("toolResultMaxChars"),
      placeholder: "12000",
      help: t("toolResultMaxCharsHelp"),
    },
    {
      tab: "context",
      path: "context.microcompact_enabled",
      control: "switch",
      label: t("microcompactEnabled"),
      help: t("microcompactEnabledHelp"),
    },
    {
      tab: "context",
      path: "context.microcompact_keep_recent",
      control: "number",
      label: t("microcompactKeepRecent"),
      placeholder: "5",
      help: t("microcompactKeepRecentHelp"),
    },
    {
      tab: "context",
      path: "context.aggressive_tool_prune_beta",
      control: "switch",
      label: t("aggressiveToolPruneBeta"),
      help: t("aggressiveToolPruneBetaHelp"),
    },
    {
      tab: "context",
      path: "context.aggressive_tool_prune_keep_recent",
      control: "number",
      label: t("aggressiveToolPruneKeepRecent"),
      placeholder: "3",
      help: t("aggressiveToolPruneKeepRecentHelp"),
    },
    {
      tab: "context",
      path: "context.project_context_enabled",
      control: "switch",
      label: t("projectContextEnabled"),
      help: t("projectContextEnabledHelp"),
    },
    {
      tab: "shell",
      path: "shell.default",
      control: "choiceList",
      optionsKey: "shell",
      label: t("defaultShell"),
      help: t("defaultShellHelp"),
    },
    {
      tab: "policy",
      path: "policy.safe_mode",
      control: "switch",
      label: t("safeMode"),
      help: t("safeModeHelp"),
    },
    {
      tab: "harness",
      path: "harness.enabled",
      control: "switch",
      label: t("harnessEnabled"),
      help: t("harnessEnabledHelp"),
    },
    {
      tab: "model",
      path: "harness.provider",
      control: "select",
      optionsKey: "harnessProvider",
      label: t("harnessProvider"),
      help: t("harnessProviderHelp"),
    },
    {
      tab: "harness",
      path: "harness.decision_mode",
      control: "choiceList",
      optionsKey: "harnessDecisionMode",
      label: t("harnessDecisionMode"),
      help: t("harnessDecisionModeHelp"),
      warning: t("harnessDecisionModeWarning"),
    },
    {
      tab: "harness",
      path: "harness.rollout.enabled",
      control: "switch",
      label: t("harnessRolloutEnabled"),
      help: t("harnessRolloutEnabledHelp"),
    },
    {
      tab: "harness",
      path: "harness.rollout.percentage",
      control: "percent",
      label: t("harnessRolloutPercentage"),
      help: t("harnessRolloutPercentageHelp"),
      min: 0,
      max: 100,
    },
    {
      tab: "harness",
      path: "harness.rollout.risk_tiers",
      control: "textarea",
      label: t("harnessRiskTiers"),
      help: t("harnessRiskTiersHelp"),
      placeholder: '["low"]',
    },
    {
      tab: "model",
      path: "harness.providers.jev.base_url",
      control: "input",
      label: t("harnessJevUrl"),
      help: t("harnessProviderUrlHelp"),
      placeholder: "https://…",
      visibleWhen: ({ getValue }) => getValue("harness.provider") === "jev",
    },
    {
      tab: "model",
      path: "harness.providers.jev.api_key",
      control: "input",
      type: "password",
      label: t("harnessJevApiKey"),
      help: t("harnessApiKeyHelp"),
      visibleWhen: ({ getValue }) => getValue("harness.provider") === "jev",
    },
    {
      tab: "model",
      path: "harness.providers.jev.model",
      control: "input",
      label: t("harnessJevModel"),
      placeholder: "typesafe/jev-1.13",
      visibleWhen: ({ getValue }) => getValue("harness.provider") === "jev",
    },
    {
      tab: "model",
      path: "harness.providers.laya.base_url",
      control: "input",
      label: t("harnessLayaUrl"),
      help: t("harnessProviderUrlHelp"),
      placeholder: "http://127.0.0.1:8765",
      visibleWhen: ({ getValue }) => getValue("harness.provider") === "laya",
    },
    {
      tab: "model",
      path: "harness.providers.laya.model",
      control: "input",
      label: t("harnessLayaModel"),
      visibleWhen: ({ getValue }) => getValue("harness.provider") === "laya",
    },
    {
      tab: "model",
      path: "jev.enabled",
      control: "switch",
      label: t("jevReview"),
      help: t("jevReviewHelp"),
    },
    {
      tab: "model",
      path: "jev.api_key",
      control: "input",
      type: "password",
      label: t("jevApiKey"),
      placeholder: "ts_...",
      help: t("jevApiKeyHelp"),
      visibleWhen: ({ getValue }) => getValue("jev.enabled") === true,
    },
    {
      tab: "model",
      path: "jev.model",
      control: "input",
      label: t("jevModel"),
      placeholder: "jev-latest",
      visibleWhen: ({ getValue }) => getValue("jev.enabled") === true,
    },
    {
      tab: "policy",
      path: "policy.allowed_paths",
      control: "textarea",
      label: t("allowedPaths"),
      placeholder: '["D:\\\\shared-assets","E:\\\\sibling-repo"]',
      help: t("allowedPathsHelp"),
    },
    {
      tab: "policy",
      path: "policy.allow_dangerous_commands",
      control: "switch",
      label: t("allowDangerousCommands"),
      help: t("allowDangerousCommandsHelp"),
    },
  ];
}
