import { t } from "../../i18n/index.js";

export function buildSettingsFields() {
  return [
    {
      tab: "connection",
      path: "gateway.base_url",
      control: "input",
      label: t("baseUrl"),
      placeholder: "http://127.0.0.1:8000/v1",
      help: t("baseUrlHelp"),
    },
    {
      tab: "connection",
      path: "gateway.api_key",
      control: "input",
      type: "password",
      label: t("apiKey"),
      placeholder: "sk-...",
      help: t("apiKeyHelp"),
    },
    {
      tab: "connection",
      path: "gateway.timeout_ms",
      control: "number",
      label: t("timeout"),
      help: t("timeoutHelp"),
    },
    {
      tab: "connection",
      path: "gateway.max_retries",
      control: "number",
      label: t("maxRetries"),
      help: t("maxRetriesHelp"),
    },
    {
      tab: "model",
      path: "sdk.provider",
      control: "providerCards",
      optionsKey: "provider",
      label: t("provider"),
      help: t("providerHelp"),
    },
    {
      tab: "model",
      path: "model.name",
      control: "input",
      label: t("modelName"),
      placeholder: "gpt-4.1-mini",
      help: t("modelNameHelp"),
    },
    {
      tab: "model",
      path: "model.fast_name",
      control: "input",
      label: t("fastModel"),
      placeholder: t("fastModelPlaceholder"),
      help: t("fastModelHelp"),
    },
    {
      tab: "model",
      path: "model.max_context_tokens",
      control: "number",
      label: t("maxContextTokens"),
      help: t("maxContextTokensHelp"),
    },
    {
      tab: "execution",
      path: "execution.mode",
      control: "choiceList",
      optionsKey: "executionMode",
      label: t("mode"),
      help: t("executionModeHelp"),
    },
    {
      tab: "execution",
      path: "execution.approval_mode",
      control: "choiceList",
      optionsKey: "approvalMode",
      label: t("approvalMode"),
      help: t("approvalModeHelp"),
    },
    {
      tab: "execution",
      path: "ui.reply_language",
      control: "segmented",
      optionsKey: "replyLanguage",
      label: t("replyLanguage"),
      help: t("replyLanguageHelp"),
    },
    {
      tab: "web",
      path: "web.search_enabled",
      control: "switch",
      label: t("webSearchEnabled"),
      help: t("webSearchEnabledHelp"),
    },
    {
      tab: "web",
      path: "web.search_provider",
      control: "providerCards",
      optionsKey: "searchProvider",
      label: t("webSearchProvider"),
      help: t("webSearchProviderHelp"),
    },
    {
      tab: "web",
      path: "web.tavily_api_key",
      control: "input",
      type: "password",
      label: t("tavilyApiKey"),
      placeholder: t("tavilyApiKeyPlaceholder"),
      help: t("tavilyApiKeyHelp"),
      visibleWhen: ({ getValue }) => getValue("web.search_provider") === "tavily",
    },
    {
      tab: "web",
      path: "web.exa_api_key",
      control: "input",
      type: "password",
      label: t("exaApiKey"),
      placeholder: t("exaApiKeyPlaceholder"),
      help: t("exaApiKeyHelp"),
      visibleWhen: ({ getValue }) => getValue("web.search_provider") === "exa",
    },
    {
      tab: "context",
      path: "context.preflight_trigger_pct",
      control: "percent",
      label: t("preflightTrigger"),
      placeholder: "60",
      help: t("preflightTriggerHelp"),
      min: 1,
      max: 100,
    },
    {
      tab: "context",
      path: "context.hard_limit_pct",
      control: "percent",
      label: t("hardLimit"),
      placeholder: "98",
      help: t("hardLimitHelp"),
      min: 1,
      max: 100,
    },
    {
      tab: "context",
      path: "context.tool_result_max_chars",
      control: "number",
      label: t("toolResultMaxChars"),
      placeholder: "12000",
      help: t("toolResultMaxCharsHelp"),
    },
    {
      tab: "context",
      path: "context.microcompact_enabled",
      control: "switch",
      label: t("microcompactEnabled"),
      help: t("microcompactEnabledHelp"),
    },
    {
      tab: "context",
      path: "context.microcompact_keep_recent",
      control: "number",
      label: t("microcompactKeepRecent"),
      placeholder: "5",
      help: t("microcompactKeepRecentHelp"),
    },
    {
      tab: "context",
      path: "context.aggressive_tool_prune_beta",
      control: "switch",
      label: t("aggressiveToolPruneBeta"),
      help: t("aggressiveToolPruneBetaHelp"),
    },
    {
      tab: "context",
      path: "context.aggressive_tool_prune_keep_recent",
      control: "number",
      label: t("aggressiveToolPruneKeepRecent"),
      placeholder: "3",
      help: t("aggressiveToolPruneKeepRecentHelp"),
    },
    {
      tab: "context",
      path: "context.project_context_enabled",
      control: "switch",
      label: t("projectContextEnabled"),
      help: t("projectContextEnabledHelp"),
    },
    {
      tab: "shell",
      path: "shell.default",
      control: "choiceList",
      optionsKey: "shell",
      label: t("defaultShell"),
      help: t("defaultShellHelp"),
    },
    {
      tab: "policy",
      path: "policy.safe_mode",
      control: "switch",
      label: t("safeMode"),
      help: t("safeModeHelp"),
    },
    {
      tab: "policy",
      path: "policy.allowed_paths",
      control: "textarea",
      label: t("allowedPaths"),
      placeholder: '["D:\\\\shared-assets","E:\\\\sibling-repo"]',
      help: t("allowedPathsHelp"),
    },
    {
      tab: "policy",
      path: "policy.allow_dangerous_commands",
      control: "switch",
      label: t("allowDangerousCommands"),
      help: t("allowDangerousCommandsHelp"),
    },
  ];
}
